name: Run Bots Twice a Day

on:
  schedule:
    - cron: "0 4,18 * * *"  # Uruchamia o 04:00 i 18:00
  workflow_dispatch:  # Pozwala uruchomić ręcznie

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Ustawia limit czasu działania zadania na 20 minut
    strategy:
      matrix:
        bot: [botY.py, botX.py]
    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uruchomienie bota
        run: python ${{ matrix.bot }}
